# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6788460edfb9682a546e6845f161b48d3da5720a7c0021d61b65f501a20db16f23be355f286516f88d5af54d55405d3de03a9da14dab5b3e1c0d494afdd63632

test:
  secret_key_base: 9a0f312596e1106bb6014ce5548f2f7a418f4d73f08f6768fc1f6dd8e69996873b5452a2f83b12bad6e3797e46a71633fa0f33cef08ebe9a83c67df7e7ae3dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
